config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get 'faq', to: 'application#faq'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  get 'new_idea', to: 'application#new_idea'
  get 'agb', to: 'application#agb'

  devise_for :users
  
  resources :users, except: [:create, :new]
  resources :news
  resources :links
  resources :pictures
  resources :pages, except: [:create, :show, :new, :destroy]

  resources :programs do
    member do
      post :rate
      get :add_existing_entry, controller: :program_entries
      get :add_new_entry, controller: :program_entries
      post :done
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :entries do
    collection do
      get :tags
      get :not_published
      get :check_duplicates
    end

    member do
      post :plan
      post :rate
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :program_entries, only: [:destroy] do
    member do
      post :move_up
      post :move_down
      post :destroy_final
      post :keep
    end
  end

  resources :comments, only: [:destroy] do
    member do
      post :publish
      post :destroy_final
      post :keep
    end
  end

  resources :attachments, only: [:destroy] do
    member do
      post :destroy_final
      post :keep
    end
  end

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62085580-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.3&appId=1617178238526480";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<div id="footer-skyline"></div>

<div id="footer">
  <div class="container">
    <div class="row">

      <div class="col-xs-6 col-sm-2">
        <ul>
          <li class="sub-title">Spielkatapult</li>
          <li><%= link_to about_path do %><span>Über uns</span><% end %></li>
          <li><%= link_to faq_path do %><span>FAQ</span><% end %></li>
          <li><%= link_to contact_path do %><span>Kontakt</span><% end %></li>
          <li><%= link_to agb_path do %><span>AGB</span><% end %></li>
        </ul>
      </div>

      <div class="col-xs-6 col-sm-2">
        <ul>
          <li class="sub-title">Links</li>
          <% @links.each do |link| %>
            <li><a href="<%= link.url %>" target="_blank"><%= link.title %></a></li>
          <% end %>
        </ul>
      </div>

      <!-- Add the extra clearfix for only the required viewport -->
      <div class="clearfix visible-xs-block"></div>

      <div class="col-xs-6 col-sm-offset-3 col-sm-3">
        <ul>
          <li class="sub-title">Jungwacht Blauring Schweiz</li>
          <li>St. Karliquai 12</li>
          <li>6004 Luzern</li>
          <li>041 419 47 47</li>
          <li><a href="mailto:info@jubla.ch" title="E-Mail">info@jubla.ch</a></li>
        </ul>
      </div>

      <div class="col-xs-6 col-sm-2 text-center">
        <img class="jubla-logo" src="<%= image_path('jubla_logo.png') %>"/>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-dismissible alert-<%= bootstrap_class_for(name) %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img alt="Brand" src="<%= image_path('logo.png') %>">
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to root_path do %><span>Home</span><% end %></li>
        <li><%= link_to entries_path do %><span>Suchen</span><% end %></li>
        <li><%= link_to new_idea_path do %><span>Erstellen</span><% end %></li>
        <% if @unfin_programs %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <b>In Arbeit</b>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% @unfin_programs_ref.each do |program| %>
                <li><%= link_to program.title, program %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <li class="hidden-xs">
          <%= form_tag("/entries", method: "get") do %>
            <%= text_field_tag("filterrific[search_query]", nil, {placeholder: "Schnellsuche", id: "fast_search"}) %>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? and current_user.is_moderator? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <% if current_user.is_admin? %>
                Admin
              <% else %>
                Moderator
              <% end %>
              <% if @publish_num != 0 %>
                <span class="badge"><%= @publish_num %></span>
              <% end %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Benutzer', users_path %></li>
              <% if current_user.is_admin? %><li><%= link_to 'News', news_index_path %></li><% end %>
              <% if current_user.is_admin? %><li><%= link_to 'Links', links_path %></li><% end %>
              <% if current_user.is_admin? %><li><%= link_to 'Texte', pages_path %></li><% end %>
              <% if current_user.is_admin? %><li><%= link_to 'Start-Bilder', pictures_path %></li><% end %>
              <li><%= link_to "Anträge (#{@publish_num})", not_published_entries_path %></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Mein Profil', user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
          <% else %>
            <%= link_to "Login", new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Spielkatapult Jungwacht Blauring</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'vendor', media: 'all', 'data-turbolinks-track' => true, debug: false %>
    <%= javascript_include_tag 'vendor', 'data-turbolinks-track' => true, debug: false %>
    <%= render 'layouts/analytics' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="canonical" href="http://spika.jubla.ch">
    <meta name="keywords" content="Spiele, Gruppenstunden, Spiekatapult, Spika, Ideensammlung, Jungwacht, Blauring, Jubla, Jugendorganisation" >
    <meta name="description" content="Eine Sammlung von Spielideen für Leitende von Jugwacht Blauring">
    <!--FACEBOOK-->
    <meta property="og:title" content="" >
    <meta property="og:site_name" content="Spielkatapult">
    <meta property="og:url" content="http://spika.jubla.ch" >
    <meta property="og:description" content="Eine Sammlung von Spielideen für Leitende von Jugwacht Blauring" >
    <meta property="og:image" content="assets/logo_blau-b9e48fe371171789e31db6f5903b9b51.png" >
    <meta property="og:type" content="website" >
    <meta property="og:locale" content="" >
    <!--TWITTER-->
    <meta property="twitter:card" content="summary" >
    <meta property="twitter:title" content="Spielkatapult" >
    <meta property="twitter:description" content="Eine Sammlung von Spielideen für Leitende von Jugwacht Blauring" >
    <meta property="twitter:creator" content="@" >
    <meta property="twitter:url" content="http://spika.jubla.ch" >
    <meta property="twitter:image" content="assets/logo_blau-b9e48fe371171789e31db6f5903b9b51.png" >

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>


  <body onload="init()">
    <%= render 'layouts/facebook' %>

    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">
      <%= render 'layouts/messages' %>

      <%= yield %>
    </div>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>

</html>